#Understanding Stages and dependsOn
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  variables:
    environment: Build
  jobs:
  - job: FirstJob
    steps: 
    - bash: echo FirstJob
    - bash: echo $(VariableInFirstJob)
  - job: SecondJob
    steps:
    - bash: echo SecondJob
- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps: 
    - bash: echo $(environment)DeployJob
- stage: QADeploy
  variables:
    environment: QA
  dependsOn: Build #check here
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo $(environment)DeployJob
- stage: ProdDeploy
  variables:
    environment: Prod
  dependsOn: #check here
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo $(environment)DeployJob
    - bash: echo $(Build.BuildNumber)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo node --version
    - bash: echo java --version
    - bash: echo python --version
    - bash: echo mvn --version
    - bash: ls -R $(Build.DefaultArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.DefaultArtifactStagingDirectory)'
    - bash: ls -R $(Build.DefaultArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    
 