trigger:
- main

# strategy:
#   matrix:
#   linux:
#    operatingSystem: 'ubuntu-latest'
#   mac:
#    operatingSystem: 'macos-latest'


# pool:
#   vmImage: $(operatingSystem)


stages:
- stage: BuildStage
  jobs:
  - job:
    steps:
    - bash: echo "Make a Build"
- stage: DevDeployStage
  jobs:
  - job:
    steps:
    - bash: echo "Deploy the dev site"
- stage: QAStage
  jobs:
  - job: 
    steps:
    - bash: echo "Deploy the QA site"


