#Understanding Stages and dependsOn
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps: 
    - bash: echo FirstJob
    - bash: echo $(VariableInFirstJob)
  - job: SecondJob
    steps:
    - bash: echo SecondJob
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps: 
    - bash: echo DevDeployJob
- stage: QADeploy
  dependsOn: Build #check here
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeployJob
- stage: ProdDeploy
  dependsOn: #check here
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo ProdDeployJob
